"""Dạng Việt hoá CÓ NGUỒN của tên / từ tiếng Anh, lấy từ `Corpus/research/tn/reading_evidence.md` mục 2.3 và 2.4 (repo riêng tư), làm ca thử
cho `abook/english_vi.py`. Chỉ chép dạng tên / từ, không chép đoạn văn.

Mỗi ca: (chữ tiếng Anh, các dạng Việt có trong nguồn, loại nguồn). Một ca KHỚP khi cách đọc của LUẬT (không qua bảng ghi đè) trùng MỘT dạng
nguồn, đủ cả thanh. Ca không khớp phải có lý do trong `EXPLAINED`.

Loại: owner (chủ sách 04-10, đứng trên mọi nguồn), official (văn bản / cơ quan nhà nước), textbook (SGK), press (báo chính thống),
community (Wikipedia, bản nháp BKTT - chỉ để xem, không là chuẩn).

Chỉ lấy tên GỐC ANH (đọc theo âm Anh, có trong từ điển CMU). Bỏ: tên Pháp / Nga / Đức / Ý / Tây Ban Nha / La-tinh đọc theo tiếng gốc (Ăng-ghen,
Lê-nin, Mát-xcơ-va, Pa-ri, Bét-tô-ven, Mô-da, Tôn-xtôi, Cô-péc-ních, Ga-li-lê, Huy-gô, Vích-to, Na-pô-lê-ông, Lu-i, Rô-be-spi-e, Mê-hi-cô,
Bra-xin, An-đét, Xa-ha-ra, Bu-ê-nôt Ai-ret, Xao Pao-lô, Mát-téc-lích, Đê-mô-crit); tên Indonesia / Singapore (Giô-cô Uy-đô-đô, Rét-nô
Ma-xu-đi, Xing-ga-po); Tếchdát (bản tin tự ghi hai kiểu); Tô-ky-ô. Tên nhiều chữ tách theo chữ khi nguồn tách được (Niu-Oóc -> New, York).
Từ mượn trong bảng ghi đè (`LOANWORDS`: đô-la...) không đưa vào đây: chúng luôn khớp, không đo được gì.
"""
from __future__ import annotations

# (chữ, dạng nguồn, loại)
SOURCED: list[tuple[str, tuple[str, ...], str]] = [
    # --- chủ sách (04-10): mục 4, cố định; Kate là ca cố định (đọc theo mặt chữ), luật âm vị không nhắm tới nó ---
    ("game", ("ghêm",), "owner"),
    ("level", ("le-vồ", "le-vờ"), "owner"),
    ("maple", ("máp-pồ",), "owner"),
    ("Michael", ("Mai-cồ",), "owner"),
    ("Kate", ("Ca-tê",), "owner"),
    # lần 2: tên ngắn tắc + e câm theo mặt chữ (Pete pi-tờ là ca riêng), -ill -> iu, s + phụ âm đầu -> xờ, slime -> xờ-lam là ca riêng
    ("Mike", ("Mi-ke",), "owner"),
    ("Jake", ("Gia-ke",), "owner"),
    ("Luke", ("Lu-ke",), "owner"),
    ("Pete", ("Pi-tờ",), "owner"),
    ("skill", ("xờ-kiu",), "owner"),
    ("boss", ("bót",), "owner"),
    ("slime", ("xờ-lam",), "owner"),
    ("quest", ("quét",), "owner"),
    # lần 3: thay dạng nguồn cùng chữ (Tô-mát của văn bản nhà nước, Bốt-tơn / Rốc-ki của SGK); guild, time, Thomas là ca riêng
    ("guild", ("gui",), "owner"),
    ("Thomas", ("Tho-mát",), "owner"),
    ("Boston", ("Bót-tơn",), "owner"),
    ("Rocky", ("Róc-ki",), "owner"),
    ("time", ("tham",), "owner"),
    ("night", ("nai",), "owner"),
    ("Blake", ("Bờ-lếch",), "owner"),
    ("Master", ("Mát-tơ",), "owner"),
    ("Zeke", ("De-ke",), "owner"),
    ("gold", ("gôn",), "owner"),
    # lần 4: t đầu từ giữ t; /iː/ -> i; /æŋk/ -> anh; l sau ai / oi -> "ồ" không phụ âm đầu
    ("Tom", ("Tom", "Tôm"), "owner"),
    ("Tony", ("To-ni", "Tô-ni"), "owner"),
    ("team", ("tim",), "owner"),
    ("tank", ("tanh",), "owner"),
    ("Tina", ("Ti-na",), "owner"),
    ("Lyle", ("Lai-ồ",), "owner"),
    ("Kyle", ("Kai-ồ", "Cai-ồ"), "owner"),  # chủ sách viết kai; chính tả 1.5 viết c trước a, cùng âm
    ("Doyle", ("Đoi-ồ",), "owner"),
    # lần 5: tên ngắn + e câm theo mặt chữ với mọi phụ âm; /eɪ/ + t -> êt, + s -> ây; /aɪər/ -> ai; /ɔːl/ -> ôn; great, Gate là ca riêng
    ("fireball", ("phai-bôn",), "owner"),
    ("Rose", ("Ro-xe",), "owner"),
    ("great", ("gờ-rít",), "owner"),
    ("late", ("lết",), "owner"),
    ("Grace", ("Gờ-rây",), "owner"),
    ("Gate", ("Ghết", "Gết"), "owner"),  # chủ sách viết gết; chính tả gh trước ê như ghêm
    ("Nate", ("Na-te", "Nết"), "owner"),
    # lần 6: tên ngắn e câm theo mặt chữ trừ âm mũi (Jane giên); g + e cứng, c + e mềm; w đầu từ -> gu; tắc + l / r giữa từ -> Cờ huyền.
    # Paul, higher, Dalton (thay Đan-tơn của SGK, cùng dạng), days, Laplace, Walt là ca riêng
    ("Paul", ("Pau",), "owner"),
    ("higher", ("hai-gờ",), "owner"),
    ("Laplace", ("La-pờ-lết",), "owner"),
    ("Jane", ("Giên", "Dên"), "owner"),
    ("Cage", ("Ca-ghe",), "owner"),
    ("Cale", ("Ca-le",), "owner"),
    ("Walt", ("Guốt",), "owner"),
    ("Dalton", ("Đan-tơn",), "owner"),
    ("days", ("đay",), "owner"),
    ("Luce", ("Lu-xe",), "owner"),
    # lần 9 (04-10 trưa; x và s, k và c, gu và go là cùng một âm, nên ghi cả hai dạng nơi chủ sách ghi một): tên Anh / châu Âu / tên bịa, và
    # phán quyết cũ 02-09 tìm lại. Ca luật không giải thích được là ca riêng (OWNER trong english_vi.py); Washington chủ sách đổi s thành x
    ("Washington", ("Oa-xinh-tơn",), "owner"),
    ("Lancel", ("Lan-xồ",), "owner"),
    ("Lucas", ("Lu-cát",), "owner"),
    ("Golem", ("Gô-lem", "Go-lem"), "owner"),
    ("Damien", ("Đa-men",), "owner"),
    ("Garfiel", ("Ga-phi-eo",), "owner"),
    ("Karen", ("Ca-ren",), "owner"),
    ("Darius", ("Đa-ri-ớt",), "owner"),
    ("Violet", ("Vai-ô-lét",), "owner"),
    ("Hunter", ("Hăn-tờ", "Hăn-tơ"), "owner"),
    ("Claudia", ("Cờ-lau-đi-a",), "owner"),
    ("Ragna", ("Rác-na", "Rắc-na"), "owner"),
    ("Audin", ("Au-đin",), "owner"),
    ("Forthorthe", ("Pho-tho-thơ",), "owner"),
    ("Hyrkan", ("Hi-can",), "owner"),
    ("Sylphy", ("Xin-phi",), "owner"),
    ("Alunaya", ("A-lu-na-gia",), "owner"),
    ("Ainz", ("Ên",), "owner"),
    ("Eve", ("E-ve",), "owner"),
    ("Ruth", ("Rút",), "owner"),
    ("Elf", ("Eo",), "owner"),
    ("Cliff", ("Cờ-líp",), "owner"),
    ("Ash", ("Át",), "owner"),
    ("Judge", ("Dắc-dồ",), "owner"),
    ("Max", ("Mắc",), "owner"),
    ("Mix", ("Mích",), "owner"),
    ("King", ("Kinh",), "owner"),
    ("Starling", ("Xờ-ta-linh",), "owner"),
    ("Maria", ("Ma-ri-a",), "owner"),
    ("Dante", ("Đan-tê",), "owner"),
    ("Mikhail", ("Mi-kha-in",), "owner"),
    ("España", ("Ét-pa-nha",), "owner"),
    ("Blanche", ("Bờ-lan-che",), "owner"),
    ("Ciel", ("Xi-eo",), "owner"),
    ("Reine", ("Ren",), "owner"),
    ("Novem", ("Nô-vem",), "owner"),
    ("Will", ("Guyu", "Guyn", "Guy-u"), "owner"),
    ("Wolf", ("Gốp",), "owner"),
    ("William", ("Guy-li-am",), "owner"),
    ("Weiss", ("Guây",), "owner"),
    ("Wendy", ("Guen-đi", "Goen-đi"), "owner"),  # guen không phải vần tiếng Việt: oe viết goen, cùng âm
    ("Walker", ("Goắc-cơ", "Goắc-cờ"), "owner"),
    ("Wood", ("Guốt",), "owner"),
    ("goblin", ("góp-lin",), "owner"),
    ("tablet", ("táp-lét",), "owner"),
    ("Andrew", ("An-riu",), "owner"),
    ("Scotland", ("Xờ-cót-lừn",), "owner"),
    ("Patrick", ("Pa-trích",), "owner"),
    ("Jud", ("Dút", "Giút"), "owner"),
    ("Undead", ("Ăn-đét",), "owner"),
    ("Dusk", ("Đắc",), "owner"),
    ("Shakespeare", ("Xếch-xơ-pia", "Sếch-xơ-pia"), "owner"),  # x và s cùng một âm
    ("Pierce", ("Pia",), "owner"),
    ("Hilde", ("Hiu-đơ",), "owner"),
    ("Gilbert", ("Ghiu-bớt",), "owner"),
    ("Franklin", ("Phờ-ranh-lin",), "owner"),
    ("Hamburg", ("Ham-bơ",), "owner"),
    ("light", ("lai",), "owner"),
    ("house", ("hau",), "owner"),
    ("sound", ("sao", "xao"), "owner"),
    ("point", ("poi",), "owner"),
    ("mouse", ("mau",), "owner"),
    ("oldest", ("ôn-đít",), "owner"),
    ("box", ("bóc",), "owner"),
    ("text", ("tếch",), "owner"),
    ("next", ("nếch",), "owner"),
    ("card", ("cạc",), "owner"),
    ("water", ("guốt-tờ",), "owner"),  # chủ sách sửa 04-10 chiều: không còn goát-tờ
    ("west", ("goét",), "owner"),
    ("wind", ("guyn",), "owner"),
    ("world", ("gua",), "owner"),
    ("Jack", ("Dách",), "owner"),
    ("Jordan", ("Gio-đan",), "owner"),
    ("doctor", ("đóc-tờ",), "owner"),
    ("monster", ("mon-tơ",), "owner"),
    ("star", ("xờ-ta",), "owner"),
    ("stone", ("xờ-tôn",), "owner"),
    ("sky", ("xờ-kai", "xờ-cai"), "owner"),
    ("school", ("xờ-cun",), "owner"),
    ("space", ("xờ-pây",), "owner"),
    ("month", ("măn",), "owner"),
    ("brother", ("bờ-ro-dờ",), "owner"),
    ("Mary", ("Ma-ri",), "owner"),
    ("Charlie", ("Chác-li",), "owner"),
    ("nation", ("nây-sừn",), "owner"),  # chủ sách sửa 04-10 chiều: không còn nây-sừng
    ("station", ("xờ-tây-sừn",), "owner"),
    ("action", ("ách-sừn",), "owner"),
    ("vision", ("vi-sừn",), "owner"),
    ("cable", ("cây-bồ",), "owner"),
    ("table", ("tây-bồ",), "owner"),
    ("lake", ("lếch",), "owner"),
    ("Elena", ("E-le-na",), "owner"),
    ("Carmen", ("Ca-men",), "owner"),
    # lần 9 bổ sung (04-10 chiều)
    ("George", ("Gióc",), "owner"),  # chủ sách chốt gióc, thay Gioóc-giơ của SGK
    ("Kirk", ("Cấc", "Cớt"), "owner"),
    ("Burke", ("Bấc", "Bớt"), "owner"),
    ("bell", ("beo",), "owner"),
    ("spell", ("xờ-peo",), "owner"),
    ("cobra", ("cốp-ra",), "owner"),
    ("April", ("Ây-rồ",), "owner"),
    ("father", ("pha-dờ",), "owner"),
    ("mother", ("ma-dờ",), "owner"),
    ("Anne", ("An-ne",), "owner"),
    ("Claire", ("Cờ-le",), "owner"),
    ("Louise", ("Lui",), "owner"),
    ("Richard", ("Ri-chát",), "owner"),
    ("Roland", ("Rô-lừn",), "owner"),
    ("Austin", ("Ô-tin",), "owner"),
    # --- văn bản nhà nước / Bộ Ngoại giao ---
    ("Edison", ("Ê-đi-xơn",), "official"),
    ("Melbourne", ("Men-bơn",), "official"),
    ("Gillian", ("Ghi-li-ừn",), "official"),
    ("Bird", ("Bớt",), "official"),
    # --- sách giáo khoa (Địa lí, Lịch sử, Ngữ văn, Tiếng Việt, KHTN) ---
    ("Virginia", ("Viếc-gi-ni-a",), "textbook"),
    ("Ireland", ("Ai-len",), "textbook"),
    ("Charles", ("Sác-lơ",), "textbook"),
    ("New", ("Niu",), "textbook"),
    ("York", ("Oóc", "I-oóc"), "textbook"),
    ("Yorktown", ("I-oóc-tao",), "textbook"),
    ("Philadelphia", ("Phi-la-đen-phi-a",), "textbook"),
    ("Dallas", ("Đa-lát",), "textbook"),
    ("San", ("Xan",), "textbook"),
    ("Francisco", ("Phran-xít-cô",), "textbook"),
    ("Los", ("Lốt",), "textbook"),
    ("Angeles", ("An-giơ-lét",), "textbook"),
    ("Chicago", ("Chi-ca-gô",), "textbook"),
    ("Detroit", ("Đi-troi",), "textbook"),
    ("Colorado", ("Cô-lô-ra-đô",), "textbook"),
    ("Portland", ("Poóc-len",), "textbook"),
    ("Seattle", ("Xit-tơn",), "textbook"),
    ("Mississippi", ("Mi-xi-xi-pi",), "textbook"),
    ("Appalachian", ("A-pa-lat",), "textbook"),
    ("Hawaii", ("Ha-oai",), "textbook"),
    ("Alaska", ("A-la-xca",), "textbook"),
    ("Canada", ("Ca-na-da",), "textbook"),
    ("Australia", ("Ô-xtrây-li-a", "Xtrây-li-a"), "textbook"),
    ("Saratoga", ("Xa-ra-tô-ga",), "textbook"),
    ("Ernest", ("Ơ-ni-xơ-tơ",), "textbook"),
    ("Hemingway", ("Hê-minh-uây",), "textbook"),
    ("Rutherford", ("Rơ-dơ-pho",), "textbook"),
    ("Matthew", ("Mét-thiu",), "textbook"),
    ("Roosevelt", ("Ru-dơ-ven", "Rô-sơ-ven"), "textbook"),
    ("Romeo", ("Rô-mê-ô",), "textbook"),
    ("Amazon", ("A-ma-dôn",), "textbook"),
    ("Cromwell", ("Crôm-oen",), "textbook"),
    # --- báo (Phạm Quỳnh 1918 qua Tuổi Trẻ 2007) ---
    ("Manchester", ("Mang-xet-te",), "press"),
    ("Edinburgh", ("E-đinh-bua",), "press"),
    # --- cộng đồng: bản nháp BKTT, Wikipedia "Từ mượn" (bảng Anh, trang tự ghi không nguồn) - chỉ để xem ---
    ("London", ("Lân-đân",), "community"),
    ("Wayne", ("Uây-nơ",), "community"),
    ("Rooney", ("Ru-ni",), "community"),
    ("Marilyn", ("Ma-ri-lin",), "community"),
    ("Monroe", ("Mon-rô",), "community"),
    ("Mark", ("Mac",), "community"),
    ("Twain", ("Tơ-uên",), "community"),
    ("camera", ("ca-mê-ra",), "community"),
    ("clip", ("cờ-líp",), "community"),
    ("font", ("phông",), "community"),
    ("internet", ("in-tơ-nét",), "community"),
    ("laptop", ("láp-tóp",), "community"),
    ("sandwich", ("xăng-guých",), "community"),
    ("robot", ("rô-bốt",), "community"),
    ("rock", ("rốc",), "community"),
    ("show", ("sô",), "community"),
    ("smartphone", ("sờ-mát-phôn",), "community"),
    ("shorts", ("soóc",), "community"),
]

# Ca không khớp, và vì sao. Khoá: chữ. Giá trị: (cách đọc luật đưa ra, lý do). Lý do là một phán quyết chủ sách, một điểm đã quét theo bằng
# chứng (scripts/sweep_english_vi_variants.py), một quy ước của app (luật 1.1: cụm phụ âm luôn tách bằng ơ) hay chỗ nguồn đọc theo chữ / theo
# tiếng khác.
_OWNER_FIXED = "ca riêng của chủ sách 04-10 (bảng ghi đè OWNER), luật không suy rộng"
_AA_O = "/ɑ/ viết o -> o (chủ sách 04-10: boss -> bót; quét: ô khớp thêm 3 dạng nguồn nhưng thua ca chủ sách)"
_EH = "/ɛ/ -> e (chủ sách 04-10: level -> le-vồ); nguồn viết ê"
_CLUSTER = "cụm phụ âm luôn tách bằng ơ, ở đầu từ thanh huyền (mục 1.1; chủ sách 04-10: xờ-kiu, bờ-lếch); nguồn giữ cụm"
_STOP_LIQUID = "tắc + l / r giữa từ tách thành Cờ thanh huyền, âm tiết trước mở (chủ sách 04-10: Laplace -> la-pờ-lết)"
_GEM = "p t k sau nguyên âm nhấn chính vừa khép vừa mở âm tiết (chủ sách 04-10: máp-pồ); nguồn không nhân đôi"
_EL = "-əl cuối -> ồ (chủ sách 04-10: máp-pồ, mai-cồ); nguồn viết -tơn"
_FRENCH = "nguồn đọc kiểu Pháp / theo chữ, không theo âm Anh"
_COMMUNITY = "dạng cộng đồng, không phải chuẩn"
EXPLAINED: dict[str, tuple[str, str]] = {
    "Kate": ("Ca-te", _OWNER_FIXED),
    "Pete": ("Pe-te", _OWNER_FIXED + "; tên ngắn khác cùng dạng đọc theo mặt chữ (Zeke -> de-ke)"),
    "guild": ("ghiu", _OWNER_FIXED + "; l cuối sau i -> u (skill -> xờ-kiu) vẫn là luật"),
    "great": ("gờ-rết", _OWNER_FIXED + ": ea không thành i (late -> lết, /eɪ/ + t -> êt là luật)"),
    "Gate": ("Ga-te", _OWNER_FIXED + ": từ thường viết hoa; tên ngắn + e câm vẫn theo mặt chữ (Nate -> na-te, Rose -> ro-xe)"),
    "time": ("tam", _OWNER_FIXED + ": t đầu từ giữ t (Tom -> tom, Tina -> ti-na); /aɪ/ + m -> am là luật"),
    "Thomas": ("To-mát", _OWNER_FIXED + ": t đầu từ giữ t (Tom -> tom), th ở đây chỉ của tên này"),
    "Edison": ("E-đi-xơn", _EH),
    "Gillian": ("Gi-li-an", "CMU đọc g mềm /dʒ/ (gi), schwa theo chữ a; Bộ Ngoại giao ghi Ghi- và -ừn (âm tiết khép mang huyền, khác luật 1.2)"),
    "Virginia": ("Vơ-gi-ni-a", "CMU /ɚ/ -> ơ; nguồn đọc theo chữ (Viếc-)"),
    "Ireland": ("Ai-lừn", "/aɪər/ -> ai (chủ sách: phai-bôn); -land -> lừn (chủ sách: Roland rô-lừn), nguồn -len"),
    "Dalton": ("Đôn-tơn", _OWNER_FIXED + ": /ɔːl/ -> ôn vẫn là luật (fireball -> phai-bôn)"),
    "higher": ("hai", _OWNER_FIXED + ": /aɪər/ -> ai vẫn là luật (fireball -> phai-bôn)"),
    "Laplace": ("La-pờ-lây", _OWNER_FIXED + " phần -lết (/eɪ/ + s cuối -> ây là luật: Grace -> gờ-rây); phần la-pờ- là luật"),
    "Walt": ("Guôn", _OWNER_FIXED + " phần l bỏ trước t (/ɔːl/ -> ôn là luật); w + o đóng -> guô là luật"),
    "days": ("đết", _OWNER_FIXED + ": /eɪ/ + z chưa thành luật (chỉ /eɪ/ + s -> ây)"),
    "Washington": ("Goa-sinh-tơn", _OWNER_FIXED + " (dạng SGK, chủ sách viết x: oa-xinh-tơn); luật đọc w + a mở -> goa, sh -> s như nation -> nây-sừn"),
    "Damien": ("Đây-mi-en", _OWNER_FIXED + ": đọc theo chữ (đa-men), CMU /ˈdeɪmiən/"),
    "Darius": ("Đa-rai-ớt", _OWNER_FIXED + ": ri theo chữ (CMU /raɪ/ -> rai); phần đa- (a trước r) và -ớt (s cuối -> t) là luật"),
    "Violet": ("Vai-ơ-lít", _OWNER_FIXED + ": ô cho schwa viết o và lét cho /ɪ/ không nhấn viết e, luật chưa suy rộng"),
    "Forthorthe": ("Pho-thót", _OWNER_FIXED + ": e cuối câm đọc thành âm tiết thơ (Hilde -> hiu-đơ, Blanche -> bờ-lan-che đọc e cuối, nhưng Burke, Pierce không)"),
    "Judge": ("Dắt", _OWNER_FIXED + ": -dge đọc dắc-dồ (c rồi dồ); j trước ă đọc d là luật (Jack dách)"),
    "Max": ("Mách", _OWNER_FIXED + ": ă thay a trước x; ac -> ach là luật (Jack dách)"),
    "Mikhail": ("Mi-kên", _OWNER_FIXED + ": kh và -ail đọc theo chữ (kha-in)"),
    "Blanche": ("Bờ-lan", _OWNER_FIXED + ": e cuối đọc che"),
    "Reine": ("Rên", _OWNER_FIXED + ": ei đọc e (ren), CMU /eɪ/ + n -> ên là luật (Jane giên)"),
    "Wolf": ("Guôn", _OWNER_FIXED + ": gốp (không u): l bỏ trước f, f -> p; Wood guốt thì có u"),
    "Walker": ("Guốc-cờ", _OWNER_FIXED + ": goắc (oă thay guô) chưa suy ra được, water guốt-tờ lại là guô"),
    "Undead": ("Un-đít", _OWNER_FIXED + ": un- đọc ăn, -ead đọc ét (đường chính tả)"),
    "Hilde": ("Hiu", _OWNER_FIXED + ": e cuối câm đọc thành đơ; l trước tắc hữu thanh -> iu là luật (Gilbert ghiu-bớt)"),
    "oldest": ("ôn-đét", _OWNER_FIXED + ": -est đọc ít"),
    "card": ("cát", "từ mượn đã vào từ điển tiếng Việt (LOANWORDS), luật cho cát"),
    "wind": ("guây", _OWNER_FIXED + ": từ điển CMU chỉ có /waɪnd/ (wine), chủ sách đọc /wɪnd/"),
    "world": ("gu-ơn", _OWNER_FIXED + ": gua, ơ + l d không suy ra được"),
    "monster": ("mon-xơ-tơ", _OWNER_FIXED + ": s giữa n và t rơi"),
    "brother": ("bờ-ra-dờ", _OWNER_FIXED + ": ro theo chữ o (mother lại là ma-dờ); dh -> d và -er mở huyền là luật"),
    "Anne": ("An", _OWNER_FIXED + ": e cuối đọc sau nn (an-ne)"),
    "Louise": ("Lu-ít", _OWNER_FIXED + ": ise rơi (lui)"),
    "April": ("Áp-rồ", _OWNER_FIXED + ": p rơi, ây- (ca lạ, không suy rộng)"),
    "Charlie": ("Cha-li", _OWNER_FIXED + ": r đọc c (chác-li), trong khi Starling bỏ r"),
    "Charles": ("Chan", _FRENCH + " (ch -> s, r -> c); luật theo âm Anh: ch, r bỏ, l -> n"),
    "New": ("Nu", "CMU (Mỹ) /nuː/ -> nu; nguồn theo âm Anh-Anh /njuː/"),
    "Francisco": ("Phờ-ran-xít-cô", _CLUSTER),
    "Angeles": ("An-gie-lít", "schwa theo chữ e, /ɪ/ -> i (quét); nguồn giơ, lét"),
    "Chicago": ("Si-ca-gô", "/ʃ/ -> s (sh -> s, như Oa-sinh-tơn); nguồn đọc theo chữ ch"),
    "Colorado": ("Co-lơ-ra-đô", _AA_O + "; CMU /ɚ/ -> ơ, nguồn theo chữ lô"),
    "Portland": ("Pót-lừn", _FRENCH + " (r -> c: Poóc); luật bỏ r sau nguyên âm (luật 1.3); tắc khép âm tiết nhấn, l mở âm tiết sau (chủ sách: xờ-cót-lừn)"),
    "Seattle": ("Xi-át-tồ", _EL),
    "Mississippi": ("Mi-xi-xíp-pi", _GEM),
    "Appalachian": ("A-pa-lây-chan", "nguồn rút gọn (A-pa-lat, bỏ -chian)"),
    "Hawaii": ("Hơ-oai-i", "CMU có schwa đầu từ (hơ) và i cuối; nguồn theo chữ Ha-oai"),
    "Alaska": ("A-lát-ca", "s trước phụ âm khép âm tiết -> t (quét: s_coda); nguồn giữ cụm xc"),
    "Canada": ("Ca-na-đa", "/d/ -> đ; nguồn viết da"),
    "Australia": ("Au-xơ-trây-li-a", _CLUSTER + "; au -> au (chủ sách: cờ-lau-đi-a), s giữa từ trước tr tách bằng xơ"),
    "Ernest": ("Ơ-nét", "cụm phụ âm cuối giữ một phụ âm (quét: final_cluster); nguồn tách từng phụ âm"),
    "Hemingway": ("He-minh-uây", _EH),
    "Rutherford": ("Ra-thơ-phớt", "/ʌ/ -> a, /θ/ -> th (quét); nguồn Rơ-dơ-pho theo chữ / kiểu Pháp"),
    "Matthew": ("Ma-thiu", "/æ/ -> a (quét: a khớp nhiều hơn e); th không nhân đôi; nguồn Mét-"),
    "Roosevelt": ("Rô-de-ven", "CMU /oʊ/ -> ô, schwa theo chữ e; nguồn Ru-dơ / Rô-sơ"),
    "Romeo": ("Rô-mi-ô", "CMU /iː/ -> i; nguồn theo chữ mê"),
    "Amazon": ("A-ma-don", _AA_O),
    "Cromwell": ("Cờ-ro-mu-ồ", _CLUSTER + "; -wəl cuối -> u-ồ (chủ sách: -əl -> ồ)"),
    "Manchester": ("Man-chét-tơ", "nguồn 1918 (Phạm Quỳnh) đọc kiểu Pháp"),
    "Edinburgh": ("E-đơn-bơ-rô", "nguồn 1918 (Phạm Quỳnh) đọc theo chữ"),
    "London": ("Lăn-đơn", _COMMUNITY),
    "Wayne": ("Goen", _COMMUNITY + "; uên không phải vần tiếng Việt (chỉ có quên), viết oen như Oen-đi"),
    "Monroe": ("Mơn-rô", _COMMUNITY),
    "Mark": ("Mác", _COMMUNITY),
    "Twain": ("Toen", _COMMUNITY + "; uên không phải vần tiếng Việt, viết oen như Oen-đi"),
    "camera": ("ca-mơ-ra", _COMMUNITY),
    "font": ("phon", _COMMUNITY),
    "sandwich": ("xan-đuýt", _COMMUNITY),
    "robot": ("rô-bót", _COMMUNITY),
    "rock": ("róc", _COMMUNITY),
    "smartphone": ("xờ-mát-phôn", _COMMUNITY),
    "shorts": ("sót", _COMMUNITY),
}
