"""Dạng Nhật / Hàn CÓ NGUỒN lấy từ `Corpus/research/tn/reading_evidence.md` mục 2.1-2.2 (repo riêng tư), làm ca thử cho `abook/romanization.py`.

Mỗi ca: (chữ Latinh, gốc, các dạng Việt có trong nguồn, loại nguồn). Một ca KHỚP khi cách đọc của luật trùng MỘT trong các dạng nguồn
(sách giáo khoa vênh nhau, nên nguồn có thể có hai dạng). Ca không khớp phải có lý do trong `EXPLAINED`: một dòng của quy ước đã [Chọn]
khác nguồn ấy, hay một chỗ quy ước không tách được; không được vì luật sai.

Loại: owner (chủ sách chốt bằng tai, 04-10; thay dạng SGK cùng chữ nếu có: Yamato), official (Bộ Ngoại giao, văn bản nhà nước), textbook (SGK), community (Wikipedia, diễn đàn - chỉ để xem, không là chuẩn).
Không đưa vào đây: dạng Hán-Việt (Minh Trị, Bình Nhưỡng, Kim Nhật Thành...), dạng giữ Latinh (Ainu, Shintō, Kang Chang Hi), và dạng
nguồn tự mâu thuẫn không xác định được (Xa-xa-cô / Xa-da-cô).
"""
from __future__ import annotations

# (latin, origin, source forms, kind)
SOURCED: list[tuple[str, str, tuple[str, ...], str]] = [
    # --- chủ sách (04-10): đứng trên mọi nguồn, cố định, không quét; trọng số cao nhất ---
    ("Haruto-kun", "ja", ("Ha-ru-tô-cun",), "owner"),
    ("Fukushima", "ja", ("Phu-cu-si-ma",), "owner"),
    # phán quyết lần 2 (04-10): y + nguyên âm -> gi (SGK viết Ya-ma-tô: chủ sách thay), ei -> ây, e Nhật -> e
    ("Yamato", "ja", ("Gia-ma-tô",), "owner"),
    ("Ayaka", "ja", ("A-gia-ca",), "owner"),
    ("Rei", "ja", ("Rây",), "owner"),
    ("sensei", "ja", ("xen-xây",), "owner"),
    ("Hajime", "ja", ("Ha-gi-me",), "owner"),
    ("Kenji", "ja", ("Ken-gi",), "owner"),
    # ou viết ra hai chữ -> âu (ō vẫn -> ô)
    ("Kyouko", "ja", ("Ki-âu-cô",), "owner"),
    ("Ryouma", "ja", ("Ri-âu-ma",), "owner"),
    # phán quyết lần 4 (04-10), Nhật: ee -> e, ii -> i (gộp như oo, uu); g + i -> ghi (ji vẫn gi); tsu -> xu ở mọi chỗ; yu sau phụ âm tách (ri-u); senpai
    # o không có phụ âm đầu (âm tiết chỉ là nguyên âm) -> o, có phụ âm đầu -> ô; aa -> a; ao CUỐI từ gộp (Nao), ao giữa từ tách a-o; onigiri là từ quen (cơm nắm),
    # chủ sách ghi đè cố định (_JA_FIXED), g + i -> ghi (Hiiragi) vẫn đứng. Dạng đầu là chính, dạng sau là alternative chủ sách chấp nhận.
    ("Osaka", "ja", ("o-xa-ca", "ô-xa-ca"), "owner"),
    ("Aoi", "ja", ("a-o-i",), "owner"),
    ("Kaori", "ja", ("ca-o-ri",), "owner"),
    ("Nao", "ja", ("nao",), "owner"),
    ("Okaa-san", "ja", ("o-ca-xan", "ô-ca-xan"), "owner"),
    ("Ojii-san", "ja", ("o-gi-xan", "ô-gi-xan"), "owner"),
    ("Onigiri", "ja", ("o-ni-gi-ri",), "owner"),
    ("Tomoe", "ja", ("tô-mô-e",), "owner"),
    ("Sora", "ja", ("xô-ra", "xo-ra"), "owner"),
    ("Konoha", "ja", ("cô-nô-ha",), "owner"),
    ("Onee-san", "ja", ("o-ne-xan",), "owner"),
    ("Onii-chan", "ja", ("o-ni-chan",), "owner"),
    ("Hiiragi", "ja", ("hi-ra-ghi",), "owner"),
    ("Inoue", "ja", ("i-nâu-e",), "owner"),
    ("Shouta", "ja", ("sâu-ta",), "owner"),
    ("Jouichi", "ja", ("giâu-i-chi",), "owner"),
    ("Kouhai", "ja", ("câu-hai",), "owner"),
    ("Senpai", "ja", ("xen-pai",), "owner"),
    ("Tsubasa", "ja", ("xu-ba-xa",), "owner"),
    ("Ryuu", "ja", ("ri-u",), "owner"),
    # phán quyết lần 4 (04-10), Hàn: k / t / p bật hơi đọc như âm thường (chủ sách viết "kang"; chính tả Việt của k trước a là c: Cang); s -> x; j -> gi;
    # y + nguyên âm -> gi; eo -> eo, hay e-o + coda khi có phụ âm cuối; yu / yeo sau phụ âm tách i-; wo -> uô, w đầu từ -> gu; oi -> oi
    ("Kang", "ko", ("cang",), "owner"),
    ("Taehyun", "ko", ("te-hi-un",), "owner"),
    ("Choi", "ko", ("choi",), "owner"),
    ("Yoon", "ko", ("giun", "dun"), "owner"),
    ("Hyung", "ko", ("hi-ung",), "owner"),
    ("Seojun", "ko", ("xeo-giun",), "owner"),
    ("Park", "ko", ("pắc",), "owner"),
    ("Jeong", "ko", ("gie-ong", "de-ong"), "owner"),
    ("Won", "ko", ("guôn",), "owner"),
    # phán quyết lần 5 (04-10) thay dạng SGK / Bộ Ngoại giao cùng chữ: o sau i / u là ô (vần iô / uô), o đầu từ hay sau a / e là o; Maaya -> may-a (ca cố định).
    ("Fukuoka", "ja", ("phu-cu-ô-ca",), "owner"),
    ("Fumio", "ja", ("phu-mi-ô",), "owner"),
    ("Naoki", "ja", ("na-o-ki",), "owner"),
    ("Maaya", "ja", ("may-a",), "owner"),
    # ya CUỐI từ sau nguyên âm: y thành bán âm cuối của âm tiết trước + a riêng (may-a, cay-a, xây-a); ya giữa / đầu từ vẫn gia (Ayaka, Yamato)
    ("Maya", "ja", ("may-a",), "owner"),
    ("Kaya", "ja", ("cay-a",), "owner"),
    ("Seiya", "ja", ("xây-a", "xay-a"), "owner"),
    # Hàn: b đầu từ -> b (Park vẫn pắc vì chữ P); gye -> ghi; eo + u -> e-un; Myung -> mung (ca cố định); tên nối gạch thành một chuỗi (giông-un, mung-bắc)
    ("Seoul", "ko", ("xe-un", "xeo-un"), "owner"),
    ("Busan", "ko", ("bu-xan",), "owner"),
    ("Suwon", "ko", ("xu-guôn",), "owner"),
    ("Kim Jong-un", "ko", ("kim giông-un",), "owner"),
    ("Lee Myung-bak", "ko", ("li mung-bắc",), "owner"),
    ("Cheonggyecheon", "ko", ("che-ong-ghi-che-on",), "owner"),
    # yu sau phụ âm tách i-u (ki-ung, bi-ung, như hi-ung); yeo sau phụ âm: y mất, g + e viết ghe (ghe-ong, pe-ong)
    ("Kyung", "ko", ("ki-ung",), "owner"),
    ("Byung", "ko", ("bi-ung",), "owner"),
    ("Gyeong", "ko", ("ghe-ong",), "owner"),
    ("Pyeong", "ko", ("pe-ong",), "owner"),
    # phán quyết lần 8 (04-10): oh trước phụ âm / cuối từ -> ô dài kể cả đầu từ (Ohto, Ohka); jy -> j (Sanjyo); gh -> g (Hiiraghi); tên cố định: Gesunoh (ghét-, KHÔNG suy rộng ge),
    # Theia, Fina, Tio (tên kiểu Âu trong truyện Nhật; Hepburn không có ti / fi); Hàn: kk -> k (tokki), Gangwon -> kang-guôn (luật viết cang theo chính tả, xem EXPLAINED)
    ("Ohto", "ja", ("ô-tô",), "owner"),
    ("Ohka", "ja", ("ô-ca",), "owner"),
    ("Gesunoh", "ja", ("ghét-xu-nô",), "owner"),
    ("Sanjyo", "ja", ("xan-giô",), "owner"),
    ("Hiiraghi", "ja", ("hi-ra-ghi",), "owner"),
    ("Theia", "ja", ("thi-a",), "owner"),
    ("Fina", "ja", ("phi-na",), "owner"),
    ("Tio", "ja", ("ti-ô",), "owner"),
    ("Gangwon", "ko", ("kang-guôn",), "owner"),
    ("tokki", "ko", ("tô-ki", "to-ki"), "owner"),
    # phán quyết lần 9 (04-10 trưa). Nhật: y đầu từ / sau a, u, o, âu -> gi (Yurika, Sakuya, Kasuya, Kouya, Raiya), y sau i rơi (Shinomiya, Renya), ya CUỐI từ chỉ còn sau nguyên âm a / ây
    # là bán âm (Maya) - yo cuối từ là gi (Futayo); yoi -> gioi (Izayoi: chủ sách viết "doi", d = gi ở giọng Bắc, cùng âm); z -> d; cch -> tch (ecchi), ff -> ph (Haffu), m trước s là ん (Hamsuke),
    # di -> đi (Reidi, Direkuresu: tên Latin trong truyện Nhật). Chủ sách viết ka / ku, app viết ca / cu theo chính tả: vẫn là một âm. Dạng sau dấu "/" là alternative chủ sách chấp nhận.
    ("Yurika", "ja", ("giu-ri-ca",), "owner"),
    ("Yukinoshita", "ja", ("giu-ki-nô-si-ta",), "owner"),
    ("Yume", "ja", ("giu-me",), "owner"),
    ("Yue", "ja", ("giu-e",), "owner"),
    ("Izayoi", "ja", ("i-da-gioi", "i-da-doi"), "owner"),
    ("Futayo", "ja", ("phu-ta-giô",), "owner"),
    ("Renya", "ja", ("re-ni-a",), "owner"),
    ("Shinomiya", "ja", ("si-nô-mi-a",), "owner"),
    ("Sakuya", "ja", ("xa-cu-gia", "xa-ku-gia"), "owner"),
    ("Kasuya", "ja", ("ca-xu-gia", "ka-xu-gia"), "owner"),
    ("Kouya", "ja", ("câu-gia",), "owner"),
    ("Raiya", "ja", ("rai-gia",), "owner"),
    ("Direkuresu", "ja", ("đi-re-cu-re-xu", "đi-re-ku-re-xu"), "owner"),
    ("Hamsuke", "ja", ("ham-xu-ke", "ham-xu-kê"), "owner"),
    ("ecchi", "ja", ("e-chi", "ét-chi"), "owner"),
    ("Haffu", "ja", ("ha-phu",), "owner"),
    ("Reidi", "ja", ("rây-đi",), "owner"),
    ("Poh-chan", "ja", ("pô-chan",), "owner"),
    # Hàn lần 9: pp / nn tách âm tiết (Oppa cố định óp-pa: o ngắn, không ô; unnie: ie cuối từ -> i), oo -> u (noona), hn cuối rơi h (Ahn), yeo đầu từ / sau nguyên âm -> gi + o + coda (Young, Muyoung, Chaeyeon: young -> yeong),
    # eun -> ưn, ye đầu từ -> gie (Yeeun = gie-ưn: chủ sách viết "de-ưn", d = gi); Jeongeun, Luda là tên cố định (luật không giải thích); w -> gu (won), ye sau phụ âm -> ê (Hye)
    ("Oppa", "ko", ("óp-pa",), "owner"),
    ("unnie", "ko", ("un-ni",), "owner"),
    ("noona", "ko", ("nu-na",), "owner"),
    ("Ahn", "ko", ("an",), "owner"),
    ("Yeeun", "ko", ("gie-ưn", "de-ưn"), "owner"),
    ("Muyoung", "ko", ("mu-giong",), "owner"),
    ("Namgung", "ko", ("nam-gung",), "owner"),
    ("Chaeyeon", "ko", ("che-gion",), "owner"),
    ("Young", "ko", ("giong",), "owner"),
    ("Hye", "ko", ("hê",), "owner"),
    ("Jeongeun", "ko", ("châng-gưn",), "owner"),
    ("Luda", "ko", ("lu-đa",), "owner"),
    ("won", "ko", ("guôn",), "owner"),
    # trả lời thêm lần 9 (04-10 chiều): y sau i rơi (Kiyoshi, Miyuki, Kiyomasa), phụ âm đôi Nhật vẫn khép (Sapporo, Hokkaido, Nissan, Matcha; Hatta là ngoại lệ), oi sau phụ âm là một âm tiết (Koizumi; Koichi là ngoại lệ);
    # Hàn: ye đầu từ -> gie, d = gi ở giọng Bắc (Yejin de-din = gie-gin, Yerin de-rin), Seoyeon -> xeo-gion (cùng luật Chaeyeon)
    ("Kiyoshi", "ja", ("ki-ô-si",), "owner"),
    ("Miyuki", "ja", ("mi-u-ki",), "owner"),
    ("Kiyomasa", "ja", ("ki-ô-ma-xa",), "owner"),
    ("Hatta", "ja", ("ha-ta",), "owner"),  # ngoại lệ cố định (tt không khép, khác Sapporo, Nissan, Matcha)
    ("Hokkaido", "ja", ("hốc-cai-đô",), "owner"),
    ("Nissan", "ja", ("nít-xan",), "owner"),
    ("Matcha", "ja", ("mát-cha",), "owner"),
    ("Koichi", "ja", ("co-i-chi",), "owner"),  # ngoại lệ cố định (ghép kou + ichi, khác Koizumi)
    ("Yejin", "ko", ("gie-gin", "de-din"), "owner"),
    ("Yerin", "ko", ("gie-rin", "de-rin"), "owner"),
    ("Seoyeon", "ko", ("xeo-gion",), "owner"),
    # --- Nhật: địa danh (SGK Địa lí / Lịch sử 11) ---
    ("Hokkaidō", "ja", ("Hô-cai-đô", "Hốc-cai-đô"), "textbook"),
    ("Honshū", "ja", ("Hôn-su",), "textbook"),
    ("Shikoku", "ja", ("Xi-cô-cư",), "textbook"),
    ("Kyūshū", "ja", ("Kiu-xiu",), "textbook"),
    ("Sapporo", "ja", ("xáp-pô-rô",), "owner"),  # chủ sách lần 9 (thay dạng SGK cùng chữ)
    ("Kushiro", "ja", ("Cu-si-rô",), "textbook"),
    ("Muroran", "ja", ("Mu-rô-ran",), "textbook"),
    ("Tōhoku", "ja", ("Tô-hô-cư",), "textbook"),
    ("Kantō", "ja", ("Can-tô",), "textbook"),
    ("Chūbu", "ja", ("Chu-bu",), "textbook"),
    ("Kansai", "ja", ("Can-sai",), "textbook"),
    ("Chūgoku", "ja", ("Chu-gô-cư",), "textbook"),
    ("Tōkyō", "ja", ("Tô-ky-ô",), "textbook"),
    ("Yokohama", "ja", ("I-ô-cô-ha-ma", "Y-ô-cô-ha-ma"), "textbook"),
    ("Kawasaki", "ja", ("Ca-oa-xa-ki",), "textbook"),
    ("Ōsaka", "ja", ("Ô-xa-ca",), "textbook"),
    ("Nagoya", "ja", ("Na-gôi-a",), "textbook"),
    ("Kōbe", "ja", ("Cô-bê", "Kô-bê"), "textbook"),
    ("Kyōto", "ja", ("Ky-ô-tô", "Ki-ô-tô"), "textbook"),
    ("Kōchi", "ja", ("Cô-chi",), "textbook"),
    ("Ōita", "ja", ("Ô-i-ta",), "textbook"),
    ("Matsuyama", "ja", ("Mát-xu-ya-ma",), "textbook"),
    ("Nagasaki", "ja", ("Na-ga-xa-ki",), "textbook"),
    ("Hiroshima", "ja", ("Hi-rô-si-ma",), "textbook"),
    ("Saitama", "ja", ("Sai-ta-ma",), "textbook"),
    ("Sendai", "ja", ("Xen-đai",), "textbook"),
    ("Shinano", "ja", ("Si-na-nô",), "textbook"),
    ("Biwa", "ja", ("Bi-oa",), "textbook"),
    ("Fukuroda", "ja", ("Fu-ku-rô-da",), "textbook"),
    ("Hakone", "ja", ("Ha-kô-ne",), "textbook"),
    ("Kasumi", "ja", ("Ca-xu-mi",), "textbook"),
    ("Kamuiwakka", "ja", ("Ka-mui-oa-ka",), "textbook"),
    ("Ryūkyū", "ja", ("Riu-kiu",), "textbook"),
    ("sumō", "ja", ("Su-mô",), "textbook"),
    ("kimono", "ja", ("Ki-mô-nô",), "textbook"),
    ("Tokugawa", "ja", ("Tô-ku-ga-oa",), "textbook"),
    ("Mutsuhito", "ja", ("Mút-xu-hi-tô", "Mút-xô-hi-tô"), "textbook"),
    ("Kōmei", "ja", ("Kô-mây",), "textbook"),
    ("Satsuma", "ja", ("Sát-su-ma",), "textbook"),
    ("Edo", "ja", ("E-đô",), "textbook"),
    ("Shimoda", "ja", ("Si-mô-đa",), "textbook"),
    ("Hakodate", "ja", ("Ha-kô-đa-tê",), "textbook"),
    ("shōgun", "ja", ("Sô-gun",), "textbook"),
    ("Meiji", "ja", ("May-gi",), "textbook"),
    # --- Nhật: tên người (Bộ Ngoại giao) ---
    ("Shinzō", "ja", ("Sin-dô",), "official"),
    ("Abe", "ja", ("A-bê",), "official"),
    ("Kishida", "ja", ("Ki-si-đa",), "official"),
    ("Takaichi", "ja", ("Ta-ca-i-chi",), "official"),
    ("Sanae", "ja", ("Sa-na-ê",), "official"),
    ("Mori", "ja", ("Mô-ri",), "official"),
    ("Eisuke", "ja", ("Ê-xư-kê",), "official"),
    ("Sekiguchi", "ja", ("Xê-ki-gư-chi",), "official"),
    ("Masakazu", "ja", ("Ma-xa-ca-dư",), "official"),
    ("Motegi", "ja", ("Mô-tê-gi",), "official"),
    ("Toshimitsu", "ja", ("Tô-si-mi-chư",), "official"),
    # --- Nhật: dạng cộng đồng (Wikipedia, Doraemon cũ) - chỉ để xem, không là chuẩn ---
    ("Koizumi", "ja", ("coi-du-mi",), "owner"),  # chủ sách lần 9 (ka / ku -> ca / cu; thay dạng cộng đồng cùng chữ): oi sau phụ âm là một âm tiết
    ("Doraemon", "ja", ("Đôrêmon",), "community"),
    ("Nobita", "ja", ("Nôbita", "Nôbitô"), "community"),
    ("Shizuka", "ja", ("Xuka",), "community"),
    ("Jaian", "ja", ("Chai-en",), "community"),
    ("Suneo", "ja", ("Xêkô",), "community"),
    ("Dekisugi", "ja", ("Đêkhi",), "community"),
    ("Dorami", "ja", ("Đôrêmi",), "community"),
    # --- Hàn: Bộ Ngoại giao ---
    ("Jeju", "ko", ("Chê-chu",), "official"),
    ("Hwaseong", "ko", ("Hoa-sơng",), "official"),
    ("Gyeongju", "ko", ("Kiơng-chu",), "official"),
    ("Changdeok", "ko", ("Chang-đớc",), "official"),
    ("Seokguram", "ko", ("Sớc-kyun", "Sớc-kun"), "official"),
    ("Bulguksa", "ko", ("Bul-kuc", "Bun-kuc"), "official"),
    ("Haein", "ko", ("He-in",), "official"),
    ("Halla", "ko", ("Han-la",), "official"),
    ("Namsan", "ko", ("Nam-san",), "official"),
    ("Yongin", "ko", ("Yông-in",), "official"),
    ("Hallyu", "ko", ("Han-lyu",), "official"),
    ("kimchi", "ko", ("Kim-chi",), "official"),
    ("Saenuri", "ko", ("Sae-nu-ri",), "official"),
    ("Park Geun-hye", "ko", ("Pắc Cưn Hê",), "official"),
    ("Kim Young-sam", "ko", ("Kim Yêng Sam",), "official"),
    ("Kim Dae-jung", "ko", ("Kim Te Chung",), "official"),
    ("Han Seung-soo", "ko", ("Han Sưng Su",), "official"),
    ("Kim Hyong-o", "ko", ("Kim Hiêng Ô",), "official"),
    ("Jeong Hong-won", "ko", ("Chơng Hông Uân",), "official"),
    ("Kim Jong-il", "ko", ("Kim Châng In",), "official"),
]

# Ca không khớp, và vì sao. Khoá: chữ Latinh. Giá trị: (cách đọc luật đưa ra, lý do). Lý do là một luật của chủ sách (04-10, đứng trên nguồn), một
# điểm đã quét theo bằng chứng (scripts/sweep_romanization_variants.py) hay chỗ nguồn tự lệch nhau; không có ca nào vì luật sai.
_U = "u Nhật -> u ở mọi chỗ (chủ sách 04-10); nguồn viết ư"
_S = "s -> x (quét: x 27 dạng SGK, s 24); nguồn lẫn s / x"
_TSU = "tsu -> xu ở mọi chỗ (chủ sách 04-10 lần 4: Tsubasa -> Xu-ba-xa); nguồn tách t khép âm tiết trước rồi xu / xô"
_K = "k -> c trước a, o, ô, ơ, u, ư (luật 1.5; quét: k_o làm bộ kiểm âm tiết từ chối 17 tên); nguồn giữ k"
_E = "e Nhật -> e (chủ sách 04-10: Hajime -> Ha-gi-me, Kenji -> Ken-gi); nguồn viết ê"
_EI = "ei -> ây (chủ sách 04-10: Rei -> Rây, sensei -> xen-xây)"
_Y = "y + nguyên âm -> gi (chủ sách 04-10: Yamato -> Gia-ma-tô, Ayaka -> A-gia-ca)"
_G = "g + i -> ghi (chủ sách 04-10 lần 4: Hiiragi -> Hi-ra-ghi; ji vẫn -> gi)"
_KO4 = "chủ sách 04-10 lần 4"
_J = "j Hàn -> gi (" + _KO4 + ": Seojun -> Xeo-giun, Jeong -> Gie-ong); nguồn viết ch"
_EO = "eo -> eo, tách e-o + coda khi có phụ âm cuối (" + _KO4 + ": Jeong -> Gie-ong, Seojun -> Xeo-giun); nguồn viết ơ"
_KS = "s Hàn -> x (" + _KO4 + ": Seojun -> Xeo-giun); nguồn viết s"
_O0 = "o không có phụ âm đầu (âm tiết chỉ là nguyên âm) -> o (chủ sách 04-10 lần 4: Osaka -> O-xa-ca, Aoi -> A-o-i); có phụ âm đầu mới -> ô"
_HY = "tên Hàn nối gạch thành một chuỗi, không tách bộ phận bằng dấu cách (chủ sách 04-10 lần 5: Kim Jong-un -> Kim Giông-un, Lee Myung-bak -> Li Mung-bắc)"
_COMMUNITY = "dạng cộng đồng (tên cũ ở Việt Nam), không phải chuẩn"
EXPLAINED: dict[str, tuple[str, str]] = {
    "Shikoku": ("Si-cô-cu", "shi -> si (luật 1.4: Hi-rô-si-ma, Ki-si-đa, quét: s 27 dạng SGK, x 22); SGK KNTT viết Xi-; " + _U),
    "Tōhoku": ("Tô-hô-cu", _U),
    "Chūgoku": ("Chu-gô-cu", _U),
    "Kansai": ("Can-xai", _S),
    "Tōkyō": ("Tô-ki-ô", "kyo -> ki-ô (mục 2, dòng kyo, theo Ki-ô-tô); SGK còn viết ky"),
    "Yokohama": ("Giô-cô-ha-ma", _Y + "; nguồn viết I-ô / Y-ô"),
    "Nagoya": ("Na-gô-gia", _Y + "; nguồn viết gôi-a"),
    "Kōbe": ("Cô-be", _E),
    "Matsuyama": ("Ma-xu-gia-ma", _TSU + "; " + _Y),
    "Saitama": ("Xai-ta-ma", _S),
    "Fukuroda": ("Phu-cu-rô-đa", "Cánh Diều giữ Latinh Fu-ku, không phiên âm"),
    "Hakone": ("Ha-cô-ne", _K + "; " + _E),
    "Kamuiwakka": ("Ca-mu-i-oác-ca", _K + "; ui tách u-i (như Ô-i-ta); kk khép âm tiết trước (mục 2)"),
    "sumō": ("xu-mô", _S),
    "Tokugawa": ("Tô-cu-ga-oa", _K),
    "Mutsuhito": ("Mu-xu-hi-tô", _TSU),
    "Kōmei": ("Cô-mây", _K),
    "Satsuma": ("Xa-xu-ma", _TSU),
    "Hakodate": ("Ha-cô-đa-te", _K + "; " + _E),
    "Meiji": ("Mây-gi", "ei -> ây (chủ sách 04-10); nguồn SGK cũ viết May-gi"),
    "Takaichi": ("Ta-cai-chi", "ai tách a-i khi là hai âm tiết (Ta-ca-i-chi), nhưng ranh giới hình vị không có trong romaji; luật giữ ai (Hô-cai-đô, Sai-ta-ma)"),
    "Abe": ("A-be", _E),
    "Sanae": ("Xa-na-e", _S + "; " + _E),
    "Eisuke": ("Ây-xu-ke", _EI + "; Bộ Ngoại giao viết Ê-; " + _U + "; " + _E),
    "Sekiguchi": ("Xe-ki-gu-chi", _U + "; " + _E),
    "Motegi": ("Mô-te-ghi", _E + "; " + _G),
    "Masakazu": ("Ma-xa-ca-du", "zu -> du (chủ sách 04-10); nguồn viết dư"),
    "Toshimitsu": ("Tô-si-mi-xu", _TSU + "; Bộ Ngoại giao viết chư"),
    "Doraemon": ("Đô-ra-e-môn", _COMMUNITY),
    "Nobita": ("Nô-bi-ta", _COMMUNITY),
    "Shizuka": ("Si-du-ca", _COMMUNITY),
    "Park Geun-hye": ("Pắc Cưn-hê", _HY + "; nguồn viết Pắc Cưn Hê"),
    "Jaian": ("Giai-an", _COMMUNITY),
    "Suneo": ("Xu-ne-o", _COMMUNITY + "; " + _O0),
    "Dekisugi": ("Đe-ki-xu-ghi", _COMMUNITY + "; " + _G),
    "Dorami": ("Đô-ra-mi", _COMMUNITY),
    "Gyeongju": ("Ghe-ong-giu", "yeo sau phụ âm mất y, eo tách e-ong (" + _KO4 + ": Hyun -> Hi-un, Jeong -> Gie-ong); " + _J + "; nguồn viết Kiơng-chu"),
    "Seokguram": ("Xe-óc-cu-ram", _KS + "; " + _EO + "; nguồn ghi Sớc-kyun / Sớc-kun, không đọc từng âm tiết của Seokguram (Latinh là chỗ dựng lại)"),
    "Bulguksa": ("Bun-cúc-xa", _KS + "; nguồn chỉ ghi Bul-kuc / Bun-kuc (bỏ -sa); b đầu từ -> b, giữa từ Bul-guk -> Bun-cúc (như Busan -> Bu-xan, chủ sách 04-10 lần 5)"),
    "Yongin": ("", "yong-in hay yon-gin: RR viết giống nhau nên không đoán (None); nguồn viết Yông-in, 'yô' không là vần tiếng Việt"),
    "Hallyu": ("Han-li-u", "yu sau phụ âm tách i-u (" + _KO4 + ": Hyun -> Hi-un, Ryuu -> Ri-u); y không phải chữ tiếng Việt"),
    "Saenuri": ("Xe-nu-ri", "ae -> e (mục 3, Te, He-in); " + _KS + "; nguồn giữ Latinh Sae"),
    "Jeong Hong-won": ("Gie-ong Hông-guôn", _J + "; " + _EO + "; wo -> uô, w đầu từ -> gu (" + _KO4 + ": Won -> Guôn); nguồn viết Chơng Hông Uân" + "; " + _HY),
    "Kim Jong-il": ("Kim Giông-in", "chữ Latinh 'Jong' (RR jeong); đọc theo chữ viết: o -> ô; " + _J + "; " + _HY),
    "Kyūshū": ("Ki-u-su", "shu -> su và yu sau phụ âm tách ki-u (" + _KO4.replace("Hàn", "") + ", Nhật: Ryuu -> Ri-u); SGK viết Kiu-xiu"),
    "Ryūkyū": ("Ri-u-ki-u", "yu sau phụ âm tách (Nhật lần 4: Ryuu -> Ri-u); SGK viết Riu-kiu"),
    "Jeju": ("Giê-giu", _J + "; nguồn viết Chê-chu"),
    "Hwaseong": ("Hoa-xe-ong", _KS + "; " + _EO + "; nguồn viết Hoa-sơng"),
    "Changdeok": ("Chang-đe-óc", _EO + "; nguồn viết Chang-đớc"),
    "Namsan": ("Nam-xan", _KS + "; nguồn viết Nam-san"),
    "Kim Young-sam": ("Kim Giong-xam", "yeo đầu từ + phụ âm cuối -> gi + o + coda (chủ sách 04-10 lần 9: Young -> Giong); " + _KS + "; nguồn viết Kim Yêng Sam" + "; " + _HY),
    "Kim Dae-jung": ("Kim Te-giung", _J + "; " + _HY),
    "Han Seung-soo": ("Han Xưng-xu", _KS + "; " + _HY),
    "Kim Hyong-o": ("Kim He-ong-ô", "yeo sau phụ âm mất y, eo tách e-ong (" + _KO4 + "); nguồn viết Kim Hiêng Ô" + "; " + _HY),
    "Ōsaka": ("O-xa-ca", _O0 + "; SGK viết Ô-xa-ca (alternative chủ sách chấp nhận)"),
    "Ōita": ("O-i-ta", _O0 + "; SGK viết Ô-i-ta"),
    "Gangwon": ("Cang-guôn", "g đầu từ -> k, k trước a viết c theo chính tả (luật 1.5; bộ kiểm âm tiết không nhận kang); chủ sách 04-10 lần 8 viết kang-guôn"),
}
